Repository node-jeneralize/pkfire, pull requests merged in 2022-06, with the labels that each got.

#44 GitHub Actions の設定を吐き出す機能を実装
  .github/workflows/jest.yaml
  README.md
  bin/pk
  package.json
  src/commands/general.ts
  src/helper/ghaConfigs.ts
  src/questions/githubActions.ts
  src/repositories/eslint.ts
  src/repositories/gha.spec.ts
  src/repositories/gha.ts
  src/repositories/tsconfig.ts
  yarn.lock
Labels: feature

#57 repository の owner 移行に伴う修正
  .github/workflows/publish.yaml
  package.json
Labels: doc

#60 fix: project name
  README.md
Labels: doc

#67 fix: owner/repo name
  README.md
Labels: doc

#69 Jest のコンフィグを吐き出す etc の機能の実装
  .npmignore
  jest.config.js.template
  package.json
  src/commands/general.ts
  src/helper/pkgScripts.ts
  src/questions/toolchains.ts
  src/repositories/jest.spec.ts
  src/repositories/jest.ts
Labels: feature

#80 パッケージの情報をクラスの中で持つように変更
  src/commands/general.ts
  src/repositories/core/toolchain.ts
  src/repositories/eslint.ts
  src/repositories/jest.ts
  src/repositories/prettier.ts
  src/repositories/tsconfig.ts
Labels: refactor

#88 依存パッケージの選択が空のときに落ちる問題の修正
  src/repositories/packageInstaller.ts
Labels: BUG
